name: Daily Python Script

on:
  schedule:
    - cron: '0 6 * * *'   # Runs daily at 6 AM UTC
  workflow_dispatch:        # Allows manual triggering (optional but recommended)

jobs:
  run-script:
    runs-on: ubuntu-latest  # Latest stable Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Pulls your repo code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'    # Use the Python version your script requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # Only include this if you have dependencies

      - name: Run the Python script
        run: python approval.py   # Replace with your script filename
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update: CSV file generated on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push  
